version: "3.0"
services: 
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3002"
    volumes:
      - "/app/node/modules"
      - "./:/app" 